# Generated by Django 4.1.7 on 2023-02-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='disponivel',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
