# Generated by Django 4.1.7 on 2023-02-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendente', models.IntegerField()),
                ('helper', models.IntegerField()),
                ('cliente', models.IntegerField()),
                ('servico', models.IntegerField()),
                ('data_hora', models.DateTimeField()),
                ('preco', models.FloatField()),
                ('situacao', models.IntegerField()),
                ('pagamento', models.IntegerField()),
                ('nome_cliente', models.CharField(max_length=50)),
                ('telefone_cliente', models.CharField(max_length=50)),
                ('logradouro_cliente', models.CharField(max_length=50)),
                ('numero_casa_cliente', models.CharField(max_length=50)),
                ('cidade_cliente', models.CharField(max_length=50)),
                ('estado_cliente', models.CharField(max_length=50)),
            ],
        ),
    ]
