# Generated by Django 4.1.7 on 2023-02-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_atendimento_data_criacao_atendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('servico', models.IntegerField()),
                ('data_reservada', models.DateTimeField()),
                ('data_de_criacao', models.DateTimeField()),
                ('valor', models.FloatField()),
            ],
        ),
    ]
