# Generated by Django 4.1.7 on 2023-02-16 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_tipo_user_usuario_cidade_usuario_complemento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sobrenome',
        ),
    ]
