# Generated by Django 4.1.7 on 2023-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_user',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
