# Generated by Django 4.1.7 on 2023-02-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_tipo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_user',
            field=models.IntegerField(),
        ),
    ]
